### ISSUE TITLE
Явное сравнение с логическим значением

### ISSUE THREAD

**Issue by truenorthpaul** [melnyk-a/KeyboardTrainer#2]
Нет необходимости указывать проверку на равенство или неравенство логического значения со значением `true` или `false` явным образом. Другими словами вместо `if (isVisible == true)` стоит писать `if (isVisible)`, или вместо `if (isVisible == false)` можно написать `if (!isVisible)`.

Свойства, в которых данное правило не соблюдается:
- `KeyboardTrainer.MainWindow.CaseSensitive`.

**Comment by melnyk-a** [comment]
свойство checkBox  IsChecked имеет тип bool?, а свойство  CaseSensitive не может принимать значение типа null, поэтому и происходит явное сравнение с true.

**Comment by truenorthpaul** [comment]
В таком случае можно использовать свойство `System.Nullable<T>.Value`.
