### ISSUE TITLE
Использование наиболее базового интерфейса

### ISSUE THREAD

**Issue by truenorthpaul** [melnyk-a/KeyboardTrainer#6]
При выборе типа константы, поля, параметра, возвращаемого значения или переменной необходимо отдавать предпочтение наиболее базовому интерфейсу, который обладает требуемой функциональностью. Другими словами, не стоит использовать в качестве типа параметра метода тип `List<string>` если метод использует данный параметр только для обхода коллекции элементов. В такой ситуации достаточно было бы использовать тип `IEnumerable<string>`.

Поля, для которых данное правило не соблюдается:
- `KeyboardTrainer.Models.KeyChars.KeyCharsProvider.keyChars`.

**Comment by melnyk-a** [comment]
В методе KeyChar Find(Key key) я использую функциональность List<KeyChar> (метод T Find(Predicate<T> match)), поэтому и в качестве приватного указала тип List. А на ружу выдаю этот тип только по более базовому интерфейсу.
